### ISSUE TITLE
Shlex completely breaks everything when commanding with quotes

### ISSUE THREAD

**Issue by NotFenixio** [meower-community/MeowerBot.py#39]
**Describe the bug**
When you try to submit a command to Meower that has quotes, the underlying Shlex will completely mess up the message and will throw an error.

**To Reproduce**
1. Create a command that accepts an argument
2. Try submitting a message to Meower that contains single quotes (') or double quotes (").

**Expected behavior**
The bot should've handled the situation accordingly and parsed the args correctly

**Screenshots**
None.

**Desktop (please complete the following information):**
(I guess this refers to what software I used in the server)
 - OS: Ubuntu (In a GitHub codespace, result of "uname -r": "6.2.0-1016-azure")
 - Browser: Google Chrome 
 - Version: 119.0.6045.160

**Additional context**
This could be solved by using shlex.quote(user_message), but it may risk users running the bot on Windows or MacOS as to my knowledge it's only supported by Linux (see [docs](https://docs.python.org/3/library/shlex.html#shlex.quote))

**Comment by showierdata9978** [comment]
https://github.com/meower-community/MeowerBot.py/blob/master/MeowerBot/bot.py#L224-L233
